spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/team?serverTimezone=Asia/Seoul
    username: chobeomhee
    password: hee6455

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  jackson:
    serialization:
      fail-on-empty-beans: false